<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzxkmsd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzxkmsd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIzxkmsd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIzxkmsd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIzxkmsd\appProdProjectContainer([
    'container.build_hash' => 'Izxkmsd',
    'container.build_id' => 'd394898e',
    'container.build_time' => 1583691255,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzxkmsd');
