<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJqs1ofy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJqs1ofy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJqs1ofy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJqs1ofy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJqs1ofy\appDevDebugProjectContainer([
    'container.build_hash' => 'Jqs1ofy',
    'container.build_id' => '67a5c5de',
    'container.build_time' => 1585613785,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJqs1ofy');
