<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbjs3st\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbjs3st/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbjs3st.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbjs3st\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXbjs3st\appDevDebugProjectContainer([
    'container.build_hash' => 'Xbjs3st',
    'container.build_id' => '43cf58a3',
    'container.build_time' => 1586549708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbjs3st');
