<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnx2j2p\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnx2j2p/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMnx2j2p.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMnx2j2p\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMnx2j2p\appDevDebugProjectContainer([
    'container.build_hash' => 'Mnx2j2p',
    'container.build_id' => '4f3bb8c5',
    'container.build_time' => 1585441463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnx2j2p');
